type CsvValue = string | number | boolean | null | undefined;

function sanitizeFilename(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "") || "ivula-canopy-export";
}

export function downloadTextFile(filename: string, content: string, type = "text/plain;charset=utf-8") {
  const blob = new Blob([content], { type });
  const url = window.URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  window.URL.revokeObjectURL(url);
}

export function toCsv(rows: Record<string, CsvValue>[]) {
  if (rows.length === 0) return "";

  const headers = Object.keys(rows[0]);
  const escape = (value: CsvValue) => {
    const text = value == null ? "" : String(value);
    return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };

  return [
    headers.map(escape).join(","),
    ...rows.map((row) => headers.map((header) => escape(row[header])).join(",")),
  ].join("\n");
}

export function downloadCsv(filenameBase: string, rows: Record<string, CsvValue>[]) {
  downloadTextFile(`${sanitizeFilename(filenameBase)}.csv`, toCsv(rows), "text/csv;charset=utf-8");
}

export function downloadExcel(filenameBase: string, rows: Record<string, CsvValue>[]) {
  const csv = toCsv(rows);
  downloadTextFile(`${sanitizeFilename(filenameBase)}.xls`, csv, "application/vnd.ms-excel;charset=utf-8");
}

export function downloadHtmlReport(filenameBase: string, title: string, rows: Record<string, CsvValue>[]) {
  const headers = rows[0] ? Object.keys(rows[0]) : [];
  const escapeHtml = (value: CsvValue) =>
    String(value ?? "")
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");

  const html = `<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>${escapeHtml(title)}</title>
    <style>
      body { font-family: Arial, sans-serif; color: #111827; margin: 32px; }
      h1 { font-size: 24px; margin-bottom: 8px; }
      p { color: #4b5563; }
      table { border-collapse: collapse; width: 100%; margin-top: 24px; }
      th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; font-size: 12px; }
      th { background: #f3f4f6; }
    </style>
  </head>
  <body>
    <h1>${escapeHtml(title)}</h1>
    <p>Generated by Ivula Canopy on ${new Date().toLocaleString()}.</p>
    <table>
      <thead><tr>${headers.map((header) => `<th>${escapeHtml(header)}</th>`).join("")}</tr></thead>
      <tbody>
        ${rows.map((row) => `<tr>${headers.map((header) => `<td>${escapeHtml(row[header])}</td>`).join("")}</tr>`).join("")}
      </tbody>
    </table>
  </body>
</html>`;

  downloadTextFile(`${sanitizeFilename(filenameBase)}.html`, html, "text/html;charset=utf-8");
}
